version: 0.0
os: linux
files:
  - source: /ser  ver
    destination: /home/ubuntu/vote-it
hooks:
  AfterInstall:
    - location: server/.scripts/after-install.sh
      runas: ubuntu
  ApplicationStart:
    - location: server/.scripts/application-start.sh
      runas: ubuntu
  ApplicationStop:
    - location: server/.scripts/application-stop.sh
      runas: ubuntu
