version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - npm install
  build:
    commands:
      # TODO: REACT_APP_API_URL AWS 환경변수로 변경
      - REACT_APP_API_URL=https://voteit.washnix.com:3000 npm run build

artifacts:
  files:
    - '**/*'
  base-directory: client/build
